spring:
  application:
    name: CryptoTickerService
server:
  port: 8081
  error:
    whitelabel:
      enabled: false
logging:
  level:
    si.mazi.rescu: ERROR
    root: INFO
info:
  app:
    name: CryptoTickerService
    description: REST endopint giving access to tickers on crypto exchanges supported by XChange project
    version: 0.1 (alpha)
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#  endpoint:
#    health:
#      show-details: ALWAYS
